### ISSUE TITLE
如果需要多个cell的标识符，需要怎么改

### ISSUE THREAD

**Issue by gdfyj90** [Akateason/XTTable#1]
目前这个封装只适合单个标识符吧。

**Comment by Akateason** [comment]
有没有多个标示符的必要? 你可以fork一下, 根据你的需求去小改, 毕竟这是我一个私人的库, 适应我的习惯, 如果多种类的cell, 多定义几个子类即可 .

**Comment by shang1219178163** [comment]
每一个开源项目开始都是私用的,提高通用性 才是王道,加上多个标示符的实现吧

**Comment by shang1219178163** [comment]
一个建议 ,如果有纯代码demo,会有更多星星,毕竟大一点的项目都是纯代码的

**Comment by Akateason** [comment]
可以看看新的方案
