### ISSUE TITLE
这个看起来有点鸡肋，看起来只是像省了几行代码，把主要的几个tableview的代理换成了block，摒弃了tableview灵活性。和原来没多大区别。按照这个思路估计复杂的页面每个页面都的重新搞个这个玩意。那还不如把所有路基处理都交给这个文件，也不回掉了

### ISSUE THREAD

**Issue by LxwYl** [Akateason/XTTable#4]

**Comment by Akateason** [comment]
hhh, 是的, 这个项目很老了, 我现在用了更灵活的解耦方案, 不过还没有开源出来.

**Comment by Akateason** [comment]
等我有空我用新方案重写个

**Comment by LxwYl** [comment]
哈哈，很期待你的新方案哈




| |
iOS 李学文
|
|
邮箱：lixuewenyl@163.com
|

签名由 网易邮箱大师 定制

在2019年10月31日 16:14，teason 写道：

等我有空我用新方案重写个

**Comment by Akateason** [comment]
ok了, 你可以看看新的方案
